#! /usr/bin/env bash

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
DRIVER_DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $DRIVER_DIR

export YCSB_WORKLOAD_DIR="YCSB/workloads"
export YCSB_OUTPUT_DIR="/tmp"
export YCSB_RUN_THREADS=32

YCSB_CLIENT_DNS="is30 is50 ip50 is140 is150 ip10 ip20 ip40"
EXTRA="-ycsb1"

WORKLOAD="olio.0"

source funcs

function launch()
{
    drop
    create
    ycsb_load $WORKLOAD $EXTRA
}

function run_ycsb()
{
    ycsb_run $WORKLOAD $EXTRA
}

[ $# -ne 1 ] && echo "Usage: $0 <launch|run_ycsb>" && exit 1

cmd="$1"
[ "$cmd" == "launch" ] && launch
[ "$cmd" == "run" ] && run_ycsb
