#! /usr/bin/env bash

# Variables needed by 'funcs'. Change as appropriate.
export YCSB_WORKLOAD_DIR="YCSB/workloads"
export YCSB_OUTPUT_DIR="/tmp/ycsb"
export YCSB_RUN_THREADS=32

# Variables needed by this script. Change as appropriate.
EXTRA="-ycsb1" # text appended to output files for further classification
WORKLOAD="olio.0"

# Nothing to change below here.

# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
DRIVER_DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $DRIVER_DIR

[ ! -d "$YCSB_OUTPUT_DIR" ] && mkdir "$YCSB_OUTPUT_DIR"
source funcs

function launch()
{
    drop
    create
    ycsb_load $WORKLOAD $EXTRA
}

function run_ycsb()
{
    ycsb_run $WORKLOAD $EXTRA
}

[ $# -ne 1 ] && echo "Usage: $0 <launch|run>" && exit 1

cmd="$1"
[ "$cmd" == "launch" ] && launch
[ "$cmd" == "run" ] && run_ycsb
